import {readFile,writeFile} from 'node:fs/promises';
import {neon} from '@neondatabase/serverless';
const local=()=>process.env.LOCAL_DATA==='1'&&!process.env.VERCEL;
export async function init(sql){await sql`CREATE TABLE IF NOT EXISTS settings (id text PRIMARY KEY, data jsonb NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS records (id text PRIMARY KEY, data jsonb NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS budgets (category text PRIMARY KEY, amount bigint NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS login_attempts (id text PRIMARY KEY, count integer NOT NULL, expires bigint NOT NULL)`}
export async function read(){if(local()){try{return JSON.parse(await readFile('.local-data.json','utf8'))}catch{return {transactions:[],budgets:{}}}}const sql=neon(process.env.DATABASE_URL);return {plan:(await sql`SELECT data FROM settings WHERE id='plan'`)[0]?.data||{salary:0,schedule:[]},transactions:(await sql`SELECT data FROM records ORDER BY id`).map(x=>x.data),budgets:Object.fromEntries((await sql`SELECT * FROM budgets`).map(x=>[x.category,Number(x.amount)]))}}
let queue=Promise.resolve();
export async function save(type,item){if(local()){queue=queue.then(async()=>{const data=await read();if(type==='plan')data.plan=item;else if(type==='budget')data.budgets[item.category]=item.amount;else{const i=data.transactions.findIndex(x=>x.id===item.id);if(i<0)data.transactions.push(item);else data.transactions[i]=item}await writeFile('.local-data.json',JSON.stringify(data))});return queue}const sql=neon(process.env.DATABASE_URL);if(type==='plan')await sql`INSERT INTO settings VALUES ('plan',${JSON.stringify(item)}::jsonb) ON CONFLICT(id) DO UPDATE SET data=excluded.data`;else if(type==='budget')await sql`INSERT INTO budgets VALUES (${item.category},${item.amount}) ON CONFLICT(category) DO UPDATE SET amount=excluded.amount`;else await sql`INSERT INTO records VALUES (${item.id},${JSON.stringify(item)}::jsonb) ON CONFLICT(id) DO UPDATE SET data=excluded.data`}
const attempts=new Map();
export async function rateLimit(key){const now=Date.now(),end=now+900000;if(local()){let v=attempts.get(key);if(!v||v.expires<now)v={count:0,expires:end};v.count++;attempts.set(key,v);return v.count<=10}const sql=neon(process.env.DATABASE_URL);const [r]=await sql`INSERT INTO login_attempts VALUES (${key},1,${end}) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN login_attempts.expires<${now} THEN 1 ELSE login_attempts.count+1 END, expires=CASE WHEN login_attempts.expires<${now} THEN ${end} ELSE login_attempts.expires END RETURNING count`;return r.count<=10}
